language: objective-c
script: xcodebuild test -workspace VENTouchLock.xcworkspace -scheme VENTouchLockTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO && xcodebuild test -workspace VENTouchLockSample/VENTouchLockSample.xcworkspace -scheme VENTouchLockSample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
before_install:
- gem i cocoapods --no-ri --no-rdoc
- brew uninstall xctool; brew install xctool --HEAD;
install:
- pod install